/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.*;
import java.awt.Point;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ioana
 */
public class BankOperation extends javax.swing.JFrame {

    /**
     * Creates new form BankOperation
     */
    public BankOperation() {
        initComponents();
        action();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Add client");

        jButton1.setText("AddClient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("AddAccount");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nume");

        jLabel4.setText("Adress");

        jLabel1.setText("CNP");

        jTextField2.setColumns(15);

        jTextField4.setColumns(15);

        jTextField1.setColumns(15);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CNP", "NUME", "ID_CARD", "ADRESA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Tranzactie");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Pay Bills");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("jLabel3");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdEmployee", "Data", "Operatia"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton8)
                        .addComponent(jButton7)
                        .addComponent(jButton6))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap())
        );

        jLabel7.setText("jLabel7");

        jTextField5.setColumns(15);

        jTextField3.setColumns(15);

        jTextField6.setColumns(15);

        jLabel8.setText("jLabel8");

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(79, 79, 79)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public SharedData data;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String CNP=null;
        String Nume=null;
        int IdCard=0;
        String adressa=null;
        int ID_Employee=0;
        ClientInfo ci=new ClientInfo();
        data=new SharedData();
        CNP=jTextField1.getText();
        Pattern p = Pattern.compile("([a-z])");
        Matcher m =null;
        if(CNP.length()==13 && p.matcher(jTextField1.getText()).find()!=true){
        if(jTextField2.isVisible() || jTextField4.isVisible()){
        Nume=jTextField2.getText();
        IdCard = 1 + (int)(Math.random() * 100000); 
        //IdCard=Integer.parseInt(jTextField3.getText());
        adressa=jTextField4.getText();
        }
        ID_Employee=data.getId_Employee();
        Client c1=new Client(Nume, IdCard, CNP, adressa);
        if(jButton1.getText().equals("AddClient")){
        if(ci.addClient(c1,ID_Employee))
        {
            jLabel1.setText("CNP");
            jLabel2.setText("AmountMoney");
            jLabel4.setText("IdType");
            jLabel5.setText("Add Account");
            jButton2.setVisible(true);
            jButton1.setVisible(false);
            jTextField4.setText("");
            jTextField2.setText("");
           // jTextField1.setText("");
           optiuni();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Clientul exista");
            optiuni();
        }
        }
        if(jButton1.getText().equals("UpdateClient")){
          if(ci.updateClient(c1,ID_Employee))
        {
            jLabel1.setText("CNP");
            jLabel2.setText("AmountMoney");
            jLabel4.setText("IdType");
            jLabel5.setText("Add Account");
            jButton2.setVisible(true);
            jButton1.setVisible(false);
            jTextField4.setText("");
            jTextField2.setText("");
           // jTextField1.setText("");
           optiuni();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Nu s-a realizat update");
            optiuni();
        }  
        }
        if(jButton1.getText().equals("Afisare")){
            if(CNP.equals("")){
            ArrayList<Client> c=new ArrayList<Client>();
            c=ci.printClients();
            DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
            for(Client client :c )
            model.addRow(new Object[]{client.getCnp(),client.getNume(),String.valueOf(client.getIdCard()),client.getAdress()}); 
            }
            else{
            Client c=new Client();
            c=ci.printClient(CNP,ID_Employee);
            DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]{c.getCnp(),c.getNume(),String.valueOf(c.getIdCard()),c.getAdress()});
            }
        }
        }
        else
            JOptionPane.showMessageDialog(this, "CNP GRESIT");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String CNP=null;
        String IdNumberAcc=null;
        float money=0.0f;
        int idType=0;
        IdNumberAcc="RO"+(10000000 + (int)(Math.random() * 1000000000))+"BT";
        AccountInfo ai=new AccountInfo();
        data=new SharedData();
        Pattern p = Pattern.compile("([a-z])");
        Matcher m =null;
        if(jTextField1.getText().length()==13 && p.matcher(jTextField1.getText()).find()!=true && p.matcher(jTextField2.getText()).find()!=true && p.matcher(jTextField4.getText()).find()!=true){
        CNP=jTextField1.getText();
        money=Float.parseFloat(jTextField2.getText());
        if(jTextField4.isVisible()==true){
        idType=Integer.parseInt(jTextField4.getText());
        }
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
            Date today = Calendar.getInstance().getTime();        
            String reportDate = df.format(today);
        Account a1=new Account(IdNumberAcc,money,CNP,reportDate,idType);
        if(jButton2.getText().equals("AddAccount")){
        if(ai.addAccount(a1,data.getId_Employee()))
        {
            JOptionPane.showMessageDialog(this, "Account adugat");
            jTextField1.setText("");
            jTextField2.setText("");
            //jTextField4.setText("");
            optiuni();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Account exista");
            optiuni();
        }
         }
        }
        else
            JOptionPane.showMessageDialog(this, "Gresala");
        if(p.matcher(jTextField1.getText()).find() && p.matcher(jTextField2.getText()).find()!=true){
         IdNumberAcc=jTextField1.getText();
         money=Float.parseFloat(jTextField2.getText());
         if(jButton2.getText().equals("UpdateAccount")){
            if(ai.updateAccount(IdNumberAcc, money, data.getId_Employee()))
        {
            JOptionPane.showMessageDialog(this, "Account update");
            jTextField1.setText("");
            jTextField2.setText("");
            //jTextField4.setText("");
            optiuni();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Account nu exista");
            optiuni();
        }
         }
        }else
            JOptionPane.showMessageDialog(this, "Gresala");
         if(p.matcher(jTextField1.getText()).find()!=true && jTextField1.getText().length()==13){ 
         if(jTextField1.isVisible()){
         IdNumberAcc=jTextField1.getText();
         }
         CNP=jTextField2.getText();
        if(jButton2.getText().equals("DeleteAccount")){
            if(ai.deleteAccount(IdNumberAcc, CNP))
        {
            JOptionPane.showMessageDialog(this, "Account delete");
            jTextField1.setText("");
            jTextField2.setText("");
            //jTextField4.setText("");
            optiuni();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Account nu exista");
            optiuni();
        }
        }
         }else
             JOptionPane.showMessageDialog(this, "Gresala");
         if(p.matcher(jTextField1.getText()).find()!=true && jTextField1.getText().length()==13){ 
            if(jButton2.getText().equals("Afisare")){
            ArrayList<Account> c=new ArrayList<Account>();
            c=ai.printAccount(CNP);
            DefaultTableModel model= new DefaultTableModel();
            model.addColumn("IdNumberAcc");
            model.addColumn("AmmountOfMoney");
            model.addColumn("DataCreation");
            model.addColumn("CNP");
            jTable1 = new JTable(model);
            for(Account client :c )
            model.addRow(new Object[]{client.getIdNrAccount(),client.getAmmountOfMoney(),client.getDataCreation(),client.getCnp(),client.getIdType()}); 
         
        }
        }
        else
            JOptionPane.showMessageDialog(this, "Exista litere in CNP variable");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String IdNumberAcc1=null;
        String IdNumberAcc2=null;
        Float suma=0.0f;
        AccountInfo ai=new AccountInfo();
        data=new SharedData();
        IdNumberAcc1=jTextField1.getText();
        IdNumberAcc2=jTextField2.getText();
        Pattern p = Pattern.compile("([a-z])");
        Matcher m =null;
        if(p.matcher(jTextField4.getText()).find()!=true){
        suma=Float.parseFloat(jTextField4.getText());
        if(ai.tranzactie(IdNumberAcc1, IdNumberAcc2, suma, data.getId_Employee()))
        {
            JOptionPane.showMessageDialog(this, "Tranzactie realizata");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField4.setText("");
            optiuni();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Tranzactie nu s-a putut realiza");
            optiuni();
        }
        }
        else
            JOptionPane.showMessageDialog(this, "Gresala");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String IdNumberAcc1=null;
        Float suma=0.0f;
        AccountInfo ai=new AccountInfo();
        IdNumberAcc1=jTextField1.getText();
        data=new SharedData();
        Pattern p = Pattern.compile("([a-z])");
        Matcher m =null;
        if(p.matcher(jTextField2.getText()).find()!=true){
        suma=Float.parseFloat(jTextField2.getText());
        String op=jComboBox1.getSelectedItem().toString();
        if(ai.payUtilities(IdNumberAcc1, suma,op,data.getId_Employee()))
        {
            JOptionPane.showMessageDialog(this, "Plata efectuata");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField4.setText("");
            optiuni();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Plata nu s-a putut realiza");
            optiuni();
        }
        }
        else
            JOptionPane.showMessageDialog(this, "Gresala");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String username=null;
        String parola=null;
        String type=null;
        int Id_Employee=1 + (int)(Math.random() * 10000);
        username=jTextField5.getText();
        parola=jTextField6.getText();
        type=jTextField7.getText();
        EmployeesInfo l=new EmployeesInfo();
        Employees e=new Employees(Id_Employee,username,parola,type);
        if(l.insertEmployee(e))
        {
            JOptionPane.showMessageDialog(this, " Employee add");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Employee existent sau nu s-a putut face add");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         String username=null;
        String parola=null;
        String type=null;
        int Id_Employee=1 + (int)(Math.random() * 10000);
        username=jTextField5.getText();
        parola=jTextField6.getText();
        type=jTextField7.getText();
        EmployeesInfo l=new EmployeesInfo();
        Employees e=new Employees(Id_Employee,username,parola,type);
        if(l.insertEmployee(e))
        {
            JOptionPane.showMessageDialog(this, " Employee update");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Employee existent sau nu s-a putut face update");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int Id_Employee=Integer.parseInt(jTextField3.getText());
        EmployeesInfo l=new EmployeesInfo();
        if(l.deleteEmployee(Id_Employee))
        {
            JOptionPane.showMessageDialog(this, " Employee delete");
            jTextField3.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Employee nu exista sau nu s-a putut realiza stergerea");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int idEmployee=Integer.parseInt(jTextField3.getText());
        String data1=jTextField5.getText();
        String data2=jTextField6.getText();
            OperatiuniBancare bo=new OperatiuniBancare();
            ArrayList<ProcessOp> c=new ArrayList<ProcessOp>();
        try {
            c=bo.readOperatiuni(idEmployee, data1, data2);
        } catch (SQLException ex) {
            Logger.getLogger(BankOperation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(BankOperation.class.getName()).log(Level.SEVERE, null, ex);
        }
            DefaultTableModel model= new DefaultTableModel();
            model.addColumn("IdEmployee");
            model.addColumn("Data");
            model.addColumn("Operatia");
            jTable2 = new JTable(model);
            for(ProcessOp client :c )
            model.addRow(new Object[]{client.getIdEmployee(),client.getDataOperation(),client.getOp()});
    }//GEN-LAST:event_jButton8ActionPerformed

    private void optiuni()
    {
        data=new SharedData();
        if(data.getResponse()==0)
        {
            jTable1.setVisible(false);
            String[] options = new String[] {"ADD", "UPDATE","VIEW","CANCEL"};
            int response = JOptionPane.showOptionDialog(null, "Ce vrei sa faci?", "Optiune",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,null, options, options[0]);
            if(response==0)
            {
            jLabel1.setText("CNP");
            jLabel2.setText("Nume");
            jLabel4.setText("Adresa");
            jLabel5.setText("Add Client");
            jButton1.setVisible(true);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jComboBox1.setVisible(false);
            jTable1.setVisible(false);
            jScrollPane1.setVisible(false);
            jTextField4.setText("");
            jTextField2.setText("");
            jTextField1.setText("");
            }
            if(response==1)
            {
            jLabel1.setText("CNP");
            jLabel2.setText("Nume");
            jLabel4.setText("Adresa");
            jLabel5.setText("Add Client");
            jButton1.setVisible(true);
            jButton1.setText("Update");
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jComboBox1.setVisible(false);
            jTable1.setVisible(false);
            jTextField4.setText("");
            jTextField2.setText("");
            jTextField1.setText("");
            }
            if(response==2)
            {
            jLabel1.setText("CNP");
            jLabel2.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setText("Afisare Client");
            jButton1.setVisible(true);
            jButton1.setText("Afisare");
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jComboBox1.setVisible(false);
            jTextField4.setVisible(false);
            jTextField2.setVisible(false);
            jTextField1.setText("");
            jTable1.setVisible(true);
                
            }
            if(response==3)
            {
                optiuni();
            }
            
        }
            if(data.getResponse()==1)
        {
            jTable1.setVisible(false);
            String[] options = new String[] {"ADD", "UPDATE","DELETE","VIEW","CANCEL"};
            int response = JOptionPane.showOptionDialog(null, "Ce vrei sa faci?", "Optiune",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,null, options, options[0]);
             if(response==0)
            {
            jLabel1.setText("CNP");
            jLabel2.setText("AmountMoney");
            jLabel4.setText("IdType");
            jLabel5.setText("Add Account");
            jButton1.setVisible(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jComboBox1.setVisible(false);
            jTable1.setVisible(false);
            jTextField4.setText("");
            jTextField2.setText("");
            jTextField1.setText("");
            }
            if(response==1)
            {
            jLabel1.setText("IdAccount");
            jLabel2.setText("AmountMoney");
            jLabel4.setVisible(false);
            jLabel5.setText("Update Account");
            jButton1.setVisible(false);
            jButton2.setText("UpdateAccount");
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jComboBox1.setVisible(false);
            jTable1.setVisible(false);
            jTextField4.setVisible(false);
            jTextField2.setText("");
            jTextField1.setText("");
            }
            if(response==2)
            {
            jLabel1.setText("IdAccount");
            jLabel2.setText("CNP");
            jLabel4.setVisible(false);
            jLabel5.setText("Delete Account");
            jButton1.setVisible(false);
            jButton2.setText("DeleteAccount");
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jComboBox1.setVisible(false);
            jTable1.setVisible(false);
            jTextField4.setVisible(false);
            jTextField2.setText("");
            jTextField1.setText("");
            }
             if(response==3)
            {
            jLabel1.setVisible(false);
            jLabel2.setText("CNP");
            jLabel4.setVisible(false);
            jLabel5.setText("Afisare Account");
            jButton1.setVisible(false);
            jButton2.setText("Afisare");
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jComboBox1.setVisible(false);
            jTable1.setVisible(true);
            jTextField4.setVisible(false);
            jTextField2.setText("");
            jTextField1.setVisible(false);
            }
            if(response==4)
            {
                optiuni();
            }
            
        }
             if(data.getResponse()==2)
        {
            jLabel1.setText("Account 1");
            jLabel2.setText("Account 2");
            jLabel4.setText("Suma");
            jLabel5.setText("Tranzactie");
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setVisible(true);
            jButton4.setVisible(false);
            jComboBox1.setVisible(false);
            jTable1.setVisible(false);
            jTextField4.setText("");
            jTextField2.setText("");
            jTextField1.setText("");
        }
             if(data.getResponse()==3)
        {
            jLabel1.setText("Account 1");
            jLabel2.setText("Suma");
            jLabel4.setText("Firma");
            jLabel5.setText("Pay Bills");
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(true);
            jComboBox1.setVisible(true);
            jTable1.setVisible(false);
            jComboBox1.addItem("Apa");
            jComboBox1.addItem("Gaz");
            jComboBox1.addItem("Electricitate");
            jTextField4.setVisible(false);
            jTextField2.setText("");
            jTextField1.setText("");
        }
            
    }
    private void action()
    {
        data=new SharedData();
        String s=data.getType();
        if(s.equals("employee"))
        {
            String[] options = new String[] {"Client", "Account","Tranzactii","Pay Bills"};
            int response = JOptionPane.showOptionDialog(null, "Ce vrei sa faci?", "Optiune",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,null, options, options[0]);
            data.setResponse(response);
            optiuni();
            jPanel1.setVisible(true);
            jPanel2.setVisible(false);
            this.setSize(700,500 );
            jPanel1.setBounds(javax.swing.JFrame.WIDTH, javax.swing.JFrame.HEIGHT, javax.swing.JFrame.WIDTH, javax.swing.JFrame.WIDTH);
        }
        else
        {
            jPanel2.setVisible(true);
            jPanel1.setVisible(false);
            this.setSize(700,500 );
            jPanel2.setBounds(javax.swing.JFrame.WIDTH, javax.swing.JFrame.HEIGHT, javax.swing.JFrame.WIDTH, javax.swing.JFrame.HEIGHT);
            String[] options = new String[] {"ADD", "UPDATE","DELETE","VIEW"};
            int response = JOptionPane.showOptionDialog(null, "Ce vrei sa faci?", "Optiune",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,null, options, options[0]);
            if(response==0)
            {
                jLabel3.setText("Add Employee");
                jLabel6.setText("Username");
                jLabel7.setText("Parola");
                jLabel8.setText("UserType");
                jButton5.setText("AddEmployee");
                jButton6.setVisible(false);
                jButton7.setVisible(false);
                jButton8.setVisible(false);
                jTable2.setVisible(false);
                jScrollPane2.setVisible(false);
            }
            if(response==1)
            {
                jLabel3.setText("Update Employee");
                jLabel6.setText("Username");
                jLabel7.setText("Parola");
                jLabel8.setText("UserType");
                jButton6.setText("UpdateEmployee");
                jButton5.setVisible(false);
                jButton7.setVisible(false);
                jButton8.setVisible(false);
                jTable2.setVisible(false);
                jScrollPane2.setVisible(false);
            }
            if(response==2)
            {
                jLabel3.setText("Delete Employee");
                jLabel6.setText("Id_Employee");
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jButton7.setText("DeleteEmployee");
                jButton5.setVisible(false);
                jButton6.setVisible(false);
                jButton8.setVisible(false);
                jTable2.setVisible(false);
                jScrollPane2.setVisible(false);
                jTextField5.setVisible(false);
                jTextField6.setVisible(false);
            }
            if(response==3)
            {
                jLabel3.setText("Print operation Employee");
                jLabel6.setText("Id_Employee");
                jLabel7.setText("Data Start");
                jLabel8.setText("Data Stop");
                jButton8.setText("PrintEmployee");
                jButton5.setVisible(false);
                jButton6.setVisible(false);
                jButton7.setVisible(false);
                jTable2.setVisible(true);
                jScrollPane2.setVisible(true);
                jTextField5.setVisible(true);
                jTextField6.setVisible(true);
            }
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankOperation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
